debug=true
server.port=8081

# PostgreSQL Local DB
spring.datasource.url=jdbc:postgresql://localhost:5432/invoicely
spring.datasource.username=postgres
spring.datasource.password=9468

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.sql.init.platform=postgres

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=433518948648-ljt7jsrtuem20dj9t7nql4pug13gkvnj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayushs9468@gmail.com
spring.mail.password=matuctkuuyzpblqt

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.main.web-application-type=servlet