spring.application.name=saas
spring.datasource.url=jdbc:postgresql://localhost:5432/firstsaas
spring.datasource.username=postgres
spring.datasource.password=Net#12345
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.registration.google.client-id=433518948648-ljt7jsrtuem20dj9t7nql4pug13gkvnj.apps.googleusercontent.com
spring.security.oauth2.registration.google.client-secret= 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